on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - uses: azure/docker-login@v1
      with:
        login-server: acr0590.azurecr.io
        username: ${{ secrets.acr_acr0590_username }}
        password: ${{ secrets.acr_acr0590_password }}
    
    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/" -f  "Dockerfile" -t acr0590.azurecr.io/myakscluster:${{ github.sha }} --label dockerfile-path=Dockerfile
        docker push acr0590.azurecr.io/myakscluster:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      with:
         kubeconfig: ${{ secrets.aks_myakscluster_kubeConfig }}
      id: login
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep myaksclusterac-python | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace myaksclusterac-python`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: myaksclusterac-python
        container-registry-url: acr0590.azurecr.io
        container-registry-username: ${{ secrets.acr_acr0590_username }}
        container-registry-password: ${{ secrets.acr_acr0590_password }}
        secret-name: myaksclusterdockerauth
       
    - uses: azure/k8s-deploy@v1.2
      with:
        namespace: myaksclusterac-python
        manifests: |
          manifests/deployment.yml
          manifests/service.yml
        images: |
          acr0590.azurecr.io/myakscluster:${{ github.sha }}
        imagepullsecrets: |
          myaksclusterdockerauth
